services:
  - type: web
    name: mishael-sellu-portfolio
    runtime: python
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: python manage.py migrate && gunicorn mishael_portfolio.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.13.5"
      - key: SITE_URL
        value: "https://mishael-sellu-portfolio.onrender.com"
      - key: CONTACT_NOTIFICATION_EMAIL
        value: "mishaelsellu68@gmail.com"
      - key: DEFAULT_FROM_EMAIL
        value: "portfolio@mishaelsellu.dev"
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
